SELECT
    old.OBJECTID AS OLD_OBJECTID,
    new.OBJECT_ID AS NEW_OBJECT_ID,
    old.SQUATTERID AS OLD_SQUATTERID,
    new.SQUATTER_ID AS NEW_SQUATTER_ID,
    old.MATERIALS AS OLD_MATERIALS,
    new.MATERIAL_ID AS NEW_MATERIAL_ID,
    old.GlobalID AS OLD_GLOBALID,
    new.SQUATTER_GUID AS NEW_SQUATTER_GUID,
    old.VERSION AS OLD_VERSION,
    new.SQUATTER_VERSION AS NEW_SQUATTER_VERSION,
    old.created_date AS OLD_CREATED_DATE,
    new.CREATED_AT AS NEW_CREATED_AT,
    old.last_edited_date AS OLD_LAST_EDITED_DATE,
    new.UPDATED_AT AS NEW_UPDATED_AT,
    CASE 
        WHEN old.OBJECTID = new.OBJECT_ID
         AND old.SQUATTERID = new.SQUATTER_ID
         AND old.MATERIALS = (SELECT NAME FROM SQ.MATERIALS WHERE ID = new.MATERIAL_ID)
         AND old.GlobalID = new.SQUATTER_GUID
         AND old.VERSION = new.SQUATTER_VERSION
         AND old.created_date = new.CREATED_AT
         AND old.last_edited_date = new.UPDATED_AT THEN 'Match'
        ELSE 'Mismatch'
    END AS DATA_CHECK
FROM 
    SDE_SQ.SQUATTERMATERIAL_HIS old
LEFT JOIN SQ.SQUATTER_MATERIAL_HIS new ON old.OBJECTID = new.OBJECT_ID
ORDER BY 
    DATA_CHECK, OLD_OBJECTID;
