-- DROP USER SC;

CREATE USER SC
-- IDENTIFIED BY <password>
;

CREATE TABLE "SC"."ATTACHMENTS" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"FULL_FILENAME" NVARCHAR2(2000) NOT NULL ENABLE, 
	"DISPLAYNAME" NVARCHAR2(2000) NOT NULL ENABLE, 
	"FILESIZE" BINARY_FLOAT NOT NULL ENABLE, 
	"URL" NVARCHAR2(2000), 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	"OBJECT_ID" NVARCHAR2(2000), 
	 CONSTRAINT "PK_ATTACHMENTS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SC"."PK_ATTACHMENTS" ON "SC"."ATTACHMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."ATTACHMENT_SQ" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"ATTACHMENT_ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"SQUATTER_GUID" NVARCHAR2(450), 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	"CREATED_BY_POST" NVARCHAR2(2000), 
	"CREATED_BY_USER" NVARCHAR2(2000), 
	"TYPE" NVARCHAR2(2000) DEFAULT N'RepairRebuildNoti' NOT NULL ENABLE, 
	"SQUATTER_ENTITY_ID" NVARCHAR2(450), 
	"SQUATTER_ENTITY_ID1" NVARCHAR2(450), 
	"SQUATTER_ENTITY_ID2" NVARCHAR2(450), 
	 CONSTRAINT "PK_ATTACHMENT_SQ" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SC"."ATTACHMENT_SQ" ADD CONSTRAINT "FK_ATTACHMENT_SQ_SQUATTERS_SQUATTER_GUID" FOREIGN KEY ("SQUATTER_GUID")
	  REFERENCES "SC"."SQUATTERS" ("ID") ENABLE;
  ALTER TABLE "SC"."ATTACHMENT_SQ" ADD CONSTRAINT "FK_ATTACHMENT_SQ_SQUATTERS_SQUATTER_ENTITY_ID" FOREIGN KEY ("SQUATTER_ENTITY_ID")
	  REFERENCES "SC"."SQUATTERS" ("ID") ENABLE;
  ALTER TABLE "SC"."ATTACHMENT_SQ" ADD CONSTRAINT "FK_ATTACHMENT_SQ_SQUATTERS_SQUATTER_ENTITY_ID1" FOREIGN KEY ("SQUATTER_ENTITY_ID1")
	  REFERENCES "SC"."SQUATTERS" ("ID") ENABLE;
  ALTER TABLE "SC"."ATTACHMENT_SQ" ADD CONSTRAINT "FK_ATTACHMENT_SQ_SQUATTERS_SQUATTER_ENTITY_ID2" FOREIGN KEY ("SQUATTER_ENTITY_ID2")
	  REFERENCES "SC"."SQUATTERS" ("ID") ENABLE;
  ALTER TABLE "SC"."ATTACHMENT_SQ" ADD CONSTRAINT "FK_ATTACHMENT_SQ_ATTACHMENTS_ATTACHMENT_ID" FOREIGN KEY ("ATTACHMENT_ID")
	  REFERENCES "SC"."ATTACHMENTS" ("ID") ON DELETE CASCADE ENABLE;

CREATE UNIQUE INDEX "SC"."IX_ATTACHMENT_SQ_ATTACHMENT_ID" ON "SC"."ATTACHMENT_SQ" ("ATTACHMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_ATTACHMENT_SQ_SQUATTER_GUID" ON "SC"."ATTACHMENT_SQ" ("SQUATTER_GUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_ATTACHMENT_SQ_SQUATTER_ENTITY_ID1" ON "SC"."ATTACHMENT_SQ" ("SQUATTER_ENTITY_ID1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_ATTACHMENT_SQ_SQUATTER_ENTITY_ID" ON "SC"."ATTACHMENT_SQ" ("SQUATTER_ENTITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_ATTACHMENT_SQ_SQUATTER_ENTITY_ID2" ON "SC"."ATTACHMENT_SQ" ("SQUATTER_ENTITY_ID2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "SC"."PK_ATTACHMENT_SQ" ON "SC"."ATTACHMENT_SQ" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."BOARD_UPS" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"REMARKS" NVARCHAR2(2000), 
	"BOARD_UP_DATE" NVARCHAR2(2000), 
	"SQUATTER_ENTITY_ID" NVARCHAR2(450), 
	"SQUATTER_PEND_ENTITY_ID" NVARCHAR2(450), 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	 CONSTRAINT "PK_BOARD_UPS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SC"."BOARD_UPS" ADD CONSTRAINT "FK_BOARD_UPS_SQUATTERS_SQUATTER_ENTITY_ID" FOREIGN KEY ("SQUATTER_ENTITY_ID")
	  REFERENCES "SC"."SQUATTERS" ("ID") ENABLE;
  ALTER TABLE "SC"."BOARD_UPS" ADD CONSTRAINT "FK_BOARD_UPS_SQUATTER_PENDS_SQUATTER_PEND_ENTITY_ID" FOREIGN KEY ("SQUATTER_PEND_ENTITY_ID")
	  REFERENCES "SC"."SQUATTER_PENDS" ("ID") ENABLE;

CREATE UNIQUE INDEX "SC"."PK_BOARD_UPS" ON "SC"."BOARD_UPS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_BOARD_UPS_SQUATTER_ENTITY_ID" ON "SC"."BOARD_UPS" ("SQUATTER_ENTITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_BOARD_UPS_SQUATTER_PEND_ENTITY_ID" ON "SC"."BOARD_UPS" ("SQUATTER_PEND_ENTITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."CSS_MASTERS" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"CSS_ID" NVARCHAR2(2000), 
	"CSS_UID" NVARCHAR2(2000), 
	"USERNAME" NVARCHAR2(2000), 
	"ENG_NAME" NVARCHAR2(2000), 
	"CHI_NAME" NVARCHAR2(2000), 
	"STAFF_RANK" NVARCHAR2(2000), 
	"CSS_POSTID" NVARCHAR2(2000), 
	"POST_NAME" NVARCHAR2(2000), 
	"SECT_DEPARTMENT" NVARCHAR2(2000), 
	"SECT_OFFICE" NVARCHAR2(2000), 
	"SECT_NAME" NVARCHAR2(2000), 
	"UNIT_NAME" NVARCHAR2(2000), 
	"OLD_OFFICE" NVARCHAR2(2000), 
	"TELEPHONE" NVARCHAR2(2000), 
	"FAX" NVARCHAR2(2000), 
	"LOCT_ADDRESS" NVARCHAR2(2000), 
	"POST_EXT_EMAIL" NVARCHAR2(2000), 
	"EMAIL" NVARCHAR2(2000), 
	"STAFF_STATUS" NVARCHAR2(2000), 
	"STAFF_TYPE" NVARCHAR2(2000), 
	"ACTIVATE_DATE" TIMESTAMP (7), 
	"INACTIVE_DATE" TIMESTAMP (7), 
	"GRADE" NVARCHAR2(2000), 
	"POST_INACTIVE" NVARCHAR2(2000), 
	"UNIT_DESC" NVARCHAR2(2000), 
	"SECT_DESC" NVARCHAR2(2000), 
	"STAFF_INACTIVE" NVARCHAR2(2000), 
	"INTRANET_SMTP_EMAIL_ADDRESS" NVARCHAR2(2000), 
	"SC_LOGIN" NUMBER(1,0), 
	"SUPER_ADMIN" NUMBER(1,0), 
	"ILES_ADMIN" NUMBER(1,0), 
	"GLL_ADMIN" NUMBER(1,0), 
	"SC_ADMIN" NUMBER(1,0), 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	 CONSTRAINT "PK_CSS_MASTERS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SC"."PK_CSS_MASTERS" ON "SC"."CSS_MASTERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."DLOS" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"DLO_NAME" NVARCHAR2(2000) NOT NULL ENABLE, 
	"DLO_DISPLAY_NAME" NVARCHAR2(2000), 
	"SORTING_INDEX" NUMBER(10,0) NOT NULL ENABLE, 
	"DLO_FULL_NAME_EN" NVARCHAR2(2000), 
	"DLO_FULL_NAME_ZH" NVARCHAR2(2000), 
	"DLO_ADDRESS_EN" NVARCHAR2(2000), 
	"DLO_ADDRESS_ZH" NVARCHAR2(2000), 
	"DLO_PHONE" NVARCHAR2(2000), 
	"DLO_FAX" NVARCHAR2(2000), 
	"DLO_EMAIL" NVARCHAR2(2000), 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	 CONSTRAINT "PK_DLOS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SC"."PK_DLOS" ON "SC"."DLOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."ERROR_LOG" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TABLE_NAME" VARCHAR2(100), 
	"ERROR_MESSAGE" VARCHAR2(4000), 
	"LOG_DATE" DATE, 
	"OBJECTID" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."EXTERNAL_SERVICE_TOKEN" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"SYSTEM_NAME" NVARCHAR2(2000) NOT NULL ENABLE, 
	"TOKEN" NVARCHAR2(2000) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	 CONSTRAINT "PK_EXTERNAL_SERVICE_TOKEN" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SC"."PK_EXTERNAL_SERVICE_TOKEN" ON "SC"."EXTERNAL_SERVICE_TOKEN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."HONG_KONG_PUBLIC_HOLIDAYS" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"DATE" TIMESTAMP (7) NOT NULL ENABLE, 
	"HOLIDAY_UID" NVARCHAR2(2000) NOT NULL ENABLE, 
	"HOLIDAY_NAME" NVARCHAR2(2000) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	 CONSTRAINT "PK_HONG_KONG_PUBLIC_HOLIDAYS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SC"."PK_HONG_KONG_PUBLIC_HOLIDAYS" ON "SC"."HONG_KONG_PUBLIC_HOLIDAYS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."MATERIALS" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"NAME" NVARCHAR2(2000) NOT NULL ENABLE, 
	"DISPLAY_NAME" NVARCHAR2(2000) NOT NULL ENABLE, 
	"SORTING_INDEX" NUMBER(10,0) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	 CONSTRAINT "PK_MATERIALS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SC"."PK_MATERIALS" ON "SC"."MATERIALS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."POSTS" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"CSS_POST_ID" NVARCHAR2(2000), 
	"POST_NAME" NVARCHAR2(2000), 
	"SECT_DEPARTMENT" NVARCHAR2(2000), 
	"SECT_OFFICE" NVARCHAR2(2000), 
	"SECT_NAME" NVARCHAR2(2000), 
	"SECT_DESC" NVARCHAR2(2000), 
	"DLO_ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"UNIT_NAME" NVARCHAR2(2000), 
	"UNIT_DESC" NVARCHAR2(2000), 
	"OLD_OFFICE" NVARCHAR2(2000), 
	"TELEPHONE" NVARCHAR2(2000), 
	"FAX" NVARCHAR2(2000), 
	"LOCT_ADDRESS" NVARCHAR2(2000), 
	"POST_EMAIL" NVARCHAR2(2000), 
	"POST_EXT_EMAIL" NVARCHAR2(2000), 
	"GRADE" NVARCHAR2(2000), 
	"POST_RANK_ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"IS_ACTIVE" NUMBER(1,0) NOT NULL ENABLE, 
	"IN_ACTIVATE_DATE" TIMESTAMP (7), 
	"ACTIVATE_DATE" TIMESTAMP (7), 
	"IS_FROM_CSS_RAW" NUMBER(1,0) NOT NULL ENABLE, 
	"POST_ALLOW_SYSTEM_RIGHT_ID" NVARCHAR2(2000), 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	 CONSTRAINT "PK_POSTS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SC"."POSTS" ADD CONSTRAINT "FK_POSTS_DLOS_DLO_ID" FOREIGN KEY ("DLO_ID")
	  REFERENCES "SC"."DLOS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SC"."POSTS" ADD CONSTRAINT "FK_POSTS_POST_RANKS_POST_RANK_ID" FOREIGN KEY ("POST_RANK_ID")
	  REFERENCES "SC"."POST_RANKS" ("ID") ON DELETE CASCADE ENABLE;

CREATE UNIQUE INDEX "SC"."PK_POSTS" ON "SC"."POSTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_POSTS_DLO_ID" ON "SC"."POSTS" ("DLO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_POSTS_POST_RANK_ID" ON "SC"."POSTS" ("POST_RANK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."POST_ALLOW_SYSTEM_RIGHTS" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"SC_LOGIN" NUMBER(1,0) NOT NULL ENABLE, 
	"SC_MAP_LAYER" NUMBER(1,0) NOT NULL ENABLE, 
	"SUPER_ADMIN" NUMBER(1,0) NOT NULL ENABLE, 
	"SC_ADMIN" NUMBER(1,0) NOT NULL ENABLE, 
	"POST_ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	 CONSTRAINT "PK_POST_ALLOW_SYSTEM_RIGHTS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SC"."POST_ALLOW_SYSTEM_RIGHTS" ADD CONSTRAINT "FK_POST_ALLOW_SYSTEM_RIGHTS_POSTS_POST_ID" FOREIGN KEY ("POST_ID")
	  REFERENCES "SC"."POSTS" ("ID") ON DELETE CASCADE ENABLE;

CREATE UNIQUE INDEX "SC"."PK_POST_ALLOW_SYSTEM_RIGHTS" ON "SC"."POST_ALLOW_SYSTEM_RIGHTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "SC"."IX_POST_ALLOW_SYSTEM_RIGHTS_POST_ID" ON "SC"."POST_ALLOW_SYSTEM_RIGHTS" ("POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."POST_ALLOW_SYSTEM_RIGHT_HISTORY_LOGS" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"POST_ALLOW_SYSTEM_RIGHT_ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"EDIT_TYPE" NVARCHAR2(2000) NOT NULL ENABLE, 
	"ORIGIN_STATE" NUMBER(1,0) NOT NULL ENABLE, 
	"NEW_STATE" NUMBER(1,0) NOT NULL ENABLE, 
	"ACTION_BY" NVARCHAR2(2000) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	 CONSTRAINT "PK_POST_ALLOW_SYSTEM_RIGHT_HISTORY_LOGS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SC"."POST_ALLOW_SYSTEM_RIGHT_HISTORY_LOGS" ADD CONSTRAINT "FK_POST_ALLOW_SYSTEM_RIGHT_HISTORY_LOGS_POST_ALLOW_SYSTEM_RIGHTS_POST_ALLOW_SYSTEM_RIGHT_ID" FOREIGN KEY ("POST_ALLOW_SYSTEM_RIGHT_ID")
	  REFERENCES "SC"."POST_ALLOW_SYSTEM_RIGHTS" ("ID") ON DELETE CASCADE ENABLE;

CREATE UNIQUE INDEX "SC"."PK_POST_ALLOW_SYSTEM_RIGHT_HISTORY_LOGS" ON "SC"."POST_ALLOW_SYSTEM_RIGHT_HISTORY_LOGS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_POST_ALLOW_SYSTEM_RIGHT_HISTORY_LOGS_POST_ALLOW_SYSTEM_RIGHT_ID" ON "SC"."POST_ALLOW_SYSTEM_RIGHT_HISTORY_LOGS" ("POST_ALLOW_SYSTEM_RIGHT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."POST_HIERARCHIES" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"POST_ID" NVARCHAR2(450), 
	"SUPERVISOR_ID" NVARCHAR2(450), 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	 CONSTRAINT "PK_POST_HIERARCHIES" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SC"."POST_HIERARCHIES" ADD CONSTRAINT "FK_POST_HIERARCHIES_POSTS_POST_ID" FOREIGN KEY ("POST_ID")
	  REFERENCES "SC"."POSTS" ("ID") ENABLE;
  ALTER TABLE "SC"."POST_HIERARCHIES" ADD CONSTRAINT "FK_POST_HIERARCHIES_POSTS_SUPERVISOR_ID" FOREIGN KEY ("SUPERVISOR_ID")
	  REFERENCES "SC"."POSTS" ("ID") ENABLE;

CREATE UNIQUE INDEX "SC"."PK_POST_HIERARCHIES" ON "SC"."POST_HIERARCHIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_POST_HIERARCHIES_POST_ID" ON "SC"."POST_HIERARCHIES" ("POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_POST_HIERARCHIES_SUPERVISOR_ID" ON "SC"."POST_HIERARCHIES" ("SUPERVISOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."POST_RANKS" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"RANK_TYPE" NVARCHAR2(2000) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	 CONSTRAINT "PK_POST_RANKS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SC"."PK_POST_RANKS" ON "SC"."POST_RANKS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."SAIS" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"SC_CASE_ID" NVARCHAR2(2000) NOT NULL ENABLE, 
	"SCT_CASE_ID" NVARCHAR2(2000) NOT NULL ENABLE, 
	"PREVIOUS_SCO_CASE_ID" NVARCHAR2(2000), 
	"ITEM_NUMBER" NVARCHAR2(2000), 
	"SCT" NVARCHAR2(2000) NOT NULL ENABLE, 
	"SN" NVARCHAR2(2000) NOT NULL ENABLE, 
	"FILE_REFERENCE" NVARCHAR2(2000), 
	"CASE_OFFICER_POST_ID" NVARCHAR2(450), 
	"CASE_TITLE" NVARCHAR2(2000) NOT NULL ENABLE, 
	"CASE_DETAILS" NVARCHAR2(2000) NOT NULL ENABLE, 
	"ACTION_TAKEN" NVARCHAR2(2000), 
	"ACTION_TAKEN_WORKFLOW" NVARCHAR2(2000), 
	"FOLLOW_UP_ACTION" NVARCHAR2(2000), 
	"DATE_OF_RECEIPT" TIMESTAMP (7) NOT NULL ENABLE, 
	"CASE_NUMBER1823" NVARCHAR2(2000), 
	"LD_NUMBER" NVARCHAR2(2000), 
	"OTHER_REFERRAL_CASE_NUMBER" NVARCHAR2(2000), 
	"DIRECT_COMPLAINT" NUMBER(10,0) NOT NULL ENABLE, 
	"OTHER_DIRECT_COMPLAINT" NVARCHAR2(2000), 
	"SELF_DETECTION" NVARCHAR2(2000), 
	"OTHER_SELF_DETECTION" NVARCHAR2(2000), 
	"REFERRAL_FROM" NVARCHAR2(2000), 
	"OTHERS" NVARCHAR2(2000), 
	"REGION" NVARCHAR2(2000) NOT NULL ENABLE, 
	"DISTRICT" NVARCHAR2(2000), 
	"SQUATTER_AREA_CODE" NVARCHAR2(2000) NOT NULL ENABLE, 
	"SQUATTER_AREA_NAME" NVARCHAR2(2000) NOT NULL ENABLE, 
	"DLO_ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"IS_UNLEASED_LAND" NUMBER(1,0), 
	"IS_PRIVATE_AGRICULTURE_LAND" NUMBER(1,0), 
	"PRIVATE_LOT_NUMBER" NVARCHAR2(2000), 
	"LICENCE" NVARCHAR2(2000), 
	"ADDRESS" NVARCHAR2(2000), 
	"CREATED_BY_POST_ID" NVARCHAR2(2000) NOT NULL ENABLE, 
	"UPDATED_BY_POST_ID" NVARCHAR2(2000) NOT NULL ENABLE, 
	"IS_DELETED" NUMBER(1,0) NOT NULL ENABLE, 
	"IS_COMPLETED" NUMBER(1,0) NOT NULL ENABLE, 
	"COMPLETION_DATE" TIMESTAMP (7), 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	 CONSTRAINT "PK_SAIS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SC"."SAIS" ADD CONSTRAINT "FK_SAIS_DLOS_DLO_ID" FOREIGN KEY ("DLO_ID")
	  REFERENCES "SC"."DLOS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SC"."SAIS" ADD CONSTRAINT "FK_SAIS_POSTS_CASE_OFFICER_POST_ID" FOREIGN KEY ("CASE_OFFICER_POST_ID")
	  REFERENCES "SC"."POSTS" ("ID") ENABLE;

CREATE UNIQUE INDEX "SC"."PK_SAIS" ON "SC"."SAIS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_SAIS_CASE_OFFICER_POST_ID" ON "SC"."SAIS" ("CASE_OFFICER_POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_SAIS_DLO_ID" ON "SC"."SAIS" ("DLO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."SQUATTERS" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"DLO_ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"SQUATTER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SURVEY_LOCATION" NVARCHAR2(2000), 
	"SURVEY_NO_PREFIX" NVARCHAR2(2000), 
	"SURVEY_NO" NVARCHAR2(2000), 
	"DISPLAY_NAME" NVARCHAR2(2000), 
	"STATUS" NVARCHAR2(2000), 
	"DATA_PROBLEM" NVARCHAR2(2000), 
	"CERTAINTY_OF_DIGITIZED_POLYGON" NVARCHAR2(2000), 
	"LAND_STATUS" NVARCHAR2(2000), 
	"IS_DOMESTIC" NUMBER(1,0), 
	"DIMENSIONS_L" NUMBER(38,8), 
	"DIMENSIONS_B" NUMBER(38,8), 
	"DIMENSIONS_H" NUMBER(38,8), 
	"UNITS" NVARCHAR2(2000), 
	"HD161FORM_RECORD_DATE" TIMESTAMP (7), 
	"SC_PLAN_NO" NVARCHAR2(2000), 
	"CASE_REFERENCE" NVARCHAR2(2000), 
	"APPROVED_AMENDMENT_DATE" TIMESTAMP (7), 
	"APPROVED_CREATION_DATE" TIMESTAMP (7), 
	"RE_INSTATE_DATE" TIMESTAMP (7), 
	"APPROVED_BY" NVARCHAR2(2000), 
	"VERSION" NUMBER(10,0) NOT NULL ENABLE, 
	"DELETE_STATE" NVARCHAR2(2000), 
	"DELETE_REMARKS" NVARCHAR2(2000), 
	"DELETE_REASON" NVARCHAR2(2000), 
	"DELETE_DATE" TIMESTAMP (7), 
	"ILES_TASK_ID" NVARCHAR2(2000), 
	"E_FOLDER_ID" NVARCHAR2(2000), 
	"ENFORCEMENT_CASE_ID" NVARCHAR2(2000), 
	"CREATED_USER" NVARCHAR2(2000), 
	"CREATED_DATE" TIMESTAMP (7), 
	"LAST_EDITED_USER" NVARCHAR2(2000), 
	"LAST_EDITED_DATE" TIMESTAMP (7), 
	"CREATED_ADM" NVARCHAR2(100), 
	"CREATED_DATE_ADM" TIMESTAMP (7), 
	"LAST_EDITED_ADM" NVARCHAR2(100), 
	"LAST_EDITED_DATE_ADM" TIMESTAMP (7), 
	"ERKS_ID_ADM" NVARCHAR2(100), 
	"CASE_REQ_DATE_ADM" TIMESTAMP (7), 
	"CASE_CPL_DATE_ADM" TIMESTAMP (7), 
	"QC_STATUS_ADM" NVARCHAR2(100), 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	"APPROVED_DELETE_DATE" TIMESTAMP (7), 
	"APPROVED_REINSTATE_DATE" TIMESTAMP (7), 
	"RECOMMENDED_BY_USER" NVARCHAR2(2000), 
	"BOOK_NO" NVARCHAR2(2000), 
	"BOUNDARY_STATUS" NVARCHAR2(2000), 
	"CIS_SQUATTER_ID" NVARCHAR2(2000), 
	"DISTRICT" NVARCHAR2(2000), 
	"FILE_NAME" NVARCHAR2(2000), 
	"HAS_REMARK" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"HOUSE_NO" NVARCHAR2(2000), 
	"ISSUE" NUMBER(10,0), 
	"IS_DELETED" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"OBJECT_ID" NVARCHAR2(2000), 
	"PLAN_FILE_NAME" NVARCHAR2(2000), 
	"RECORD_DATE_EDIT" NVARCHAR2(2000), 
	"SC_OFFICE" NVARCHAR2(2000), 
	"SERIAL_NO" NVARCHAR2(2000), 
	"SERIAL_NO_EDIT" NVARCHAR2(2000), 
	"SURVEY_RECORD1982" NVARCHAR2(2000), 
	"CASE_FILE" NVARCHAR2(2000), 
	"CLEARANCE_NO" NVARCHAR2(2000), 
	"JOB_NO" NVARCHAR2(2000), 
	"RECORD_DATE" TIMESTAMP (7), 
	"APPROVED_BY_POST" NVARCHAR2(2000), 
	"APPROVED_BY_USER" NVARCHAR2(2000), 
	"D_APPROVE_STATUS" NVARCHAR2(2000), 
	"RECOMMENDED_BY_POST" NVARCHAR2(2000), 
	"AMEND_DATE" TIMESTAMP (7), 
	"REINSTATE_REMARK" NVARCHAR2(2000), 
	 CONSTRAINT "PK_SQUATTERS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SC"."SQUATTERS" ADD CONSTRAINT "FK_SQUATTERS_DLOS_DLO_ID" FOREIGN KEY ("DLO_ID")
	  REFERENCES "SC"."DLOS" ("ID") ON DELETE CASCADE ENABLE;

CREATE UNIQUE INDEX "SC"."PK_SQUATTERS" ON "SC"."SQUATTERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_SQUATTERS_DLO_ID" ON "SC"."SQUATTERS" ("DLO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "SC"."IX_SQUATTERS_SQUATTER_ID" ON "SC"."SQUATTERS" ("SQUATTER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."SQUATTER_BOARD_UP_HISTORIES" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"BOARD_UP_ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"SQUATTER_HISTORY_ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	 CONSTRAINT "PK_SQUATTER_BOARD_UP_HISTORIES" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SC"."SQUATTER_BOARD_UP_HISTORIES" ADD CONSTRAINT "FK_SQUATTER_BOARD_UP_HISTORIES_BOARD_UPS_BOARD_UP_ID" FOREIGN KEY ("BOARD_UP_ID")
	  REFERENCES "SC"."BOARD_UPS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SC"."SQUATTER_BOARD_UP_HISTORIES" ADD CONSTRAINT "FK_SQUATTER_BOARD_UP_HISTORIES_SQUATTER_HISTORIES_SQUATTER_HISTORY_ID" FOREIGN KEY ("SQUATTER_HISTORY_ID")
	  REFERENCES "SC"."SQUATTER_HISTORIES" ("ID") ON DELETE CASCADE ENABLE;

CREATE UNIQUE INDEX "SC"."PK_SQUATTER_BOARD_UP_HISTORIES" ON "SC"."SQUATTER_BOARD_UP_HISTORIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_SQUATTER_BOARD_UP_HISTORIES_BOARD_UP_ID" ON "SC"."SQUATTER_BOARD_UP_HISTORIES" ("BOARD_UP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_SQUATTER_BOARD_UP_HISTORIES_SQUATTER_HISTORY_ID" ON "SC"."SQUATTER_BOARD_UP_HISTORIES" ("SQUATTER_HISTORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."SQUATTER_HISTORIES" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"DLO_ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"SQUATTER_GUID" NVARCHAR2(450), 
	"SQUATTER_ID" NUMBER(10,0), 
	"SURVEY_LOCATION" NVARCHAR2(2000), 
	"SURVEY_NO_PREFIX" NVARCHAR2(2000), 
	"SURVEY_NO" NVARCHAR2(2000), 
	"DISPLAY_NAME" NVARCHAR2(2000), 
	"STATUS" NVARCHAR2(2000), 
	"DATA_PROBLEM" NVARCHAR2(2000), 
	"CERTAINTY_OF_DIGITIZED_POLYGON" NVARCHAR2(2000), 
	"LAND_STATUS" NVARCHAR2(2000), 
	"IS_DOMESTIC" NUMBER(1,0), 
	"DIMENSIONS_L" NUMBER(38,8), 
	"DIMENSIONS_B" NUMBER(38,8), 
	"DIMENSIONS_H" NUMBER(38,8), 
	"UNITS" NVARCHAR2(2000), 
	"HD161FORM_RECORD_DATE" TIMESTAMP (7), 
	"SC_PLAN_NO" NVARCHAR2(2000), 
	"CASE_REFERENCE" NVARCHAR2(2000), 
	"APPROVED_AMENDMENT_DATE" TIMESTAMP (7), 
	"APPROVED_CREATION_DATE" TIMESTAMP (7), 
	"RE_INSTATE_DATE" TIMESTAMP (7), 
	"APPROVED_BY" NVARCHAR2(2000), 
	"VERSION" NUMBER(10,0) NOT NULL ENABLE, 
	"DELETE_STATE" NVARCHAR2(2000), 
	"DELETE_REMARKS" NVARCHAR2(2000), 
	"DELETE_REASON" NVARCHAR2(2000), 
	"DELETE_DATE" TIMESTAMP (7), 
	"ILES_TASK_ID" NVARCHAR2(2000), 
	"E_FOLDER_ID" NVARCHAR2(2000), 
	"ENFORCEMENT_CASE_ID" NVARCHAR2(2000), 
	"CREATED_USER" NVARCHAR2(2000), 
	"CREATED_DATE" TIMESTAMP (7), 
	"LAST_EDITED_USER" NVARCHAR2(2000), 
	"LAST_EDITED_DATE" TIMESTAMP (7), 
	"CREATED_ADM" NVARCHAR2(100), 
	"CREATED_DATE_ADM" TIMESTAMP (7), 
	"LAST_EDITED_ADM" NVARCHAR2(100), 
	"LAST_EDITED_DATE_ADM" TIMESTAMP (7), 
	"ERKS_ID_ADM" NVARCHAR2(100), 
	"CASE_REQ_DATE_ADM" TIMESTAMP (7), 
	"CASE_CPL_DATE_ADM" TIMESTAMP (7), 
	"QC_STATUS_ADM" NVARCHAR2(100), 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	"IS_DELETED" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"OBJECT_ID" NVARCHAR2(2000), 
	"APPROVED_AMEND_DATE" TIMESTAMP (7), 
	"APPROVED_DELETE_DATE" TIMESTAMP (7), 
	"APPROVED_REINSTATE_DATE" TIMESTAMP (7), 
	"APPROVE_STATUS" NVARCHAR2(2000), 
	"BOOK_NO" NVARCHAR2(2000), 
	"BOUNDARY_STATUS" NVARCHAR2(2000), 
	"CIS_SQUATTER_ID" NVARCHAR2(2000), 
	"DISTRICT" NVARCHAR2(2000), 
	"FILE_NAME" NVARCHAR2(2000), 
	"HAS_REMARK" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"HOUSE_NO" NVARCHAR2(2000), 
	"ISSUE" NUMBER(10,0), 
	"PLAN_FILE_NAME" NVARCHAR2(2000), 
	"RECORD_DATE_EDIT" NVARCHAR2(2000), 
	"SC_OFFICE" NVARCHAR2(2000), 
	"SERIAL_NO" NVARCHAR2(2000), 
	"SERIAL_NO_EDIT" NVARCHAR2(2000), 
	"SURVEY_RECORD1982" NVARCHAR2(2000), 
	"AMEND_DATE" TIMESTAMP (7), 
	"CASE_FILE" NVARCHAR2(2000), 
	"CLEARANCE_NO" NVARCHAR2(2000), 
	"JOB_NO" NVARCHAR2(2000), 
	"RECORD_DATE" TIMESTAMP (7), 
	"REINSTATE_REMARK" NVARCHAR2(2000), 
	 CONSTRAINT "PK_SQUATTER_HISTORIES" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SC"."SQUATTER_HISTORIES" ADD CONSTRAINT "FK_SQUATTER_HISTORIES_DLOS_DLO_ID" FOREIGN KEY ("DLO_ID")
	  REFERENCES "SC"."DLOS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SC"."SQUATTER_HISTORIES" ADD CONSTRAINT "FK_SQUATTER_HISTORIES_SQUATTERS_SQUATTER_GUID" FOREIGN KEY ("SQUATTER_GUID")
	  REFERENCES "SC"."SQUATTERS" ("ID") ENABLE;

CREATE UNIQUE INDEX "SC"."PK_SQUATTER_HISTORIES" ON "SC"."SQUATTER_HISTORIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_SQUATTER_HISTORIES_DLO_ID" ON "SC"."SQUATTER_HISTORIES" ("DLO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_SQUATTER_HISTORIES_SQUATTER_GUID" ON "SC"."SQUATTER_HISTORIES" ("SQUATTER_GUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."SQUATTER_MATERIALS" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"MATERIAL_ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"SQUATTER_GUID" NVARCHAR2(450), 
	"SQUATTER_PEND_GUID" NVARCHAR2(450), 
	"SQUATTER_ID" NUMBER(10,0), 
	"SQUATTER_VERSION" NUMBER(10,0) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	"OBJECT_ID" NUMBER(10,0), 
	"D_SQUATTER_MATERIAL_ID" NVARCHAR2(2000), 
	"GLOBAL_ID" NVARCHAR2(2000), 
	 CONSTRAINT "PK_SQUATTER_MATERIALS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SC"."SQUATTER_MATERIALS" ADD CONSTRAINT "FK_SQUATTER_MATERIALS_MATERIALS_MATERIAL_ID" FOREIGN KEY ("MATERIAL_ID")
	  REFERENCES "SC"."MATERIALS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SC"."SQUATTER_MATERIALS" ADD CONSTRAINT "FK_SQUATTER_MATERIALS_SQUATTERS_SQUATTER_GUID" FOREIGN KEY ("SQUATTER_GUID")
	  REFERENCES "SC"."SQUATTERS" ("ID") ENABLE;
  ALTER TABLE "SC"."SQUATTER_MATERIALS" ADD CONSTRAINT "FK_SQUATTER_MATERIALS_SQUATTER_PENDS_SQUATTER_PEND_GUID" FOREIGN KEY ("SQUATTER_PEND_GUID")
	  REFERENCES "SC"."SQUATTER_PENDS" ("ID") ENABLE;

CREATE UNIQUE INDEX "SC"."PK_SQUATTER_MATERIALS" ON "SC"."SQUATTER_MATERIALS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_SQUATTER_MATERIALS_MATERIAL_ID" ON "SC"."SQUATTER_MATERIALS" ("MATERIAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_SQUATTER_MATERIALS_SQUATTER_GUID" ON "SC"."SQUATTER_MATERIALS" ("SQUATTER_GUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_SQUATTER_MATERIALS_SQUATTER_PEND_GUID" ON "SC"."SQUATTER_MATERIALS" ("SQUATTER_PEND_GUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."SQUATTER_MATERIAL_HIS" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"MATERIAL_ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"SQUATTER_HISTORY_ID" NVARCHAR2(450), 
	"SQUATTER_ID" NUMBER(10,0), 
	"SQUATTER_VERSION" NUMBER(10,0) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	"OBJECT_ID" NUMBER(10,0), 
	"D_SQUATTER_MATERIAL_ID" NVARCHAR2(2000), 
	"GLOBAL_ID" NVARCHAR2(2000), 
	 CONSTRAINT "PK_SQUATTER_MATERIAL_HIS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SC"."SQUATTER_MATERIAL_HIS" ADD CONSTRAINT "FK_SQUATTER_MATERIAL_HIS_SQUATTER_HISTORIES_SQUATTER_HISTORY_ID" FOREIGN KEY ("SQUATTER_HISTORY_ID")
	  REFERENCES "SC"."SQUATTER_HISTORIES" ("ID") ENABLE;
  ALTER TABLE "SC"."SQUATTER_MATERIAL_HIS" ADD CONSTRAINT "FK_SQUATTER_MATERIAL_HIS_MATERIALS_MATERIAL_ID" FOREIGN KEY ("MATERIAL_ID")
	  REFERENCES "SC"."MATERIALS" ("ID") ON DELETE CASCADE ENABLE;

CREATE UNIQUE INDEX "SC"."PK_SQUATTER_MATERIAL_HIS" ON "SC"."SQUATTER_MATERIAL_HIS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_SQUATTER_MATERIAL_HIS_MATERIAL_ID" ON "SC"."SQUATTER_MATERIAL_HIS" ("MATERIAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_SQUATTER_MATERIAL_HIS_SQUATTER_HISTORY_ID" ON "SC"."SQUATTER_MATERIAL_HIS" ("SQUATTER_HISTORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."SQUATTER_PENDS" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"DLO_ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"SQUATTER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SURVEY_LOCATION" NVARCHAR2(2000), 
	"SURVEY_NO_PREFIX" NVARCHAR2(2000), 
	"SURVEY_NO" NVARCHAR2(2000), 
	"DISPLAY_NAME" NVARCHAR2(2000), 
	"STATUS" NVARCHAR2(2000), 
	"DATA_PROBLEM" NVARCHAR2(2000), 
	"CERTAINTY_OF_DIGITIZED_POLYGON" NVARCHAR2(2000), 
	"LAND_STATUS" NVARCHAR2(2000), 
	"IS_DOMESTIC" NUMBER(1,0), 
	"DIMENSIONS_L" NUMBER(38,8), 
	"DIMENSIONS_B" NUMBER(38,8), 
	"DIMENSIONS_H" NUMBER(38,8), 
	"UNITS" NVARCHAR2(2000), 
	"HD161FORM_RECORD_DATE" TIMESTAMP (7), 
	"SC_PLAN_NO" NVARCHAR2(2000), 
	"CASE_REFERENCE" NVARCHAR2(2000), 
	"APPROVED_AMENDMENT_DATE" TIMESTAMP (7), 
	"APPROVED_CREATION_DATE" TIMESTAMP (7), 
	"RE_INSTATE_DATE" TIMESTAMP (7), 
	"RECOMMENDED_BY_USER" NVARCHAR2(2000), 
	"VERSION" NUMBER(10,0) NOT NULL ENABLE, 
	"DELETE_STATE" NVARCHAR2(2000), 
	"DELETE_REMARKS" NVARCHAR2(2000), 
	"DELETE_REASON" NVARCHAR2(2000), 
	"DELETE_DATE" TIMESTAMP (7), 
	"ILES_TASK_ID" NVARCHAR2(2000), 
	"E_FOLDER_ID" NVARCHAR2(2000), 
	"ENFORCEMENT_CASE_ID" NVARCHAR2(2000), 
	"CREATED_USER" NVARCHAR2(2000), 
	"CREATED_DATE" TIMESTAMP (7), 
	"LAST_EDITED_USER" NVARCHAR2(2000), 
	"LAST_EDITED_DATE" TIMESTAMP (7), 
	"CREATED_ADM" NVARCHAR2(100), 
	"CREATED_DATE_ADM" TIMESTAMP (7), 
	"LAST_EDITED_ADM" NVARCHAR2(100), 
	"LAST_EDITED_DATE_ADM" TIMESTAMP (7), 
	"ERKS_ID_ADM" NVARCHAR2(100), 
	"CASE_REQ_DATE_ADM" TIMESTAMP (7), 
	"CASE_CPL_DATE_ADM" TIMESTAMP (7), 
	"QC_STATUS_ADM" NVARCHAR2(100), 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	"SQUATTER_GUID" NVARCHAR2(450), 
	"IS_DELETED" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"OBJECT_ID" NVARCHAR2(2000), 
	"APPROVED_AMEND_DATE" TIMESTAMP (7), 
	"APPROVED_DELETE_DATE" TIMESTAMP (7), 
	"APPROVED_REINSTATE_DATE" TIMESTAMP (7), 
	"APPROVE_STATUS" NVARCHAR2(2000), 
	"BOOK_NO" NVARCHAR2(2000), 
	"BOUNDARY_STATUS" NVARCHAR2(2000), 
	"CIS_SQUATTER_ID" NVARCHAR2(2000), 
	"DISTRICT" NVARCHAR2(2000), 
	"FILE_NAME" NVARCHAR2(2000), 
	"HAS_REMARK" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"HOUSE_NO" NVARCHAR2(2000), 
	"ISSUE" NUMBER(10,0), 
	"PLAN_FILE_NAME" NVARCHAR2(2000), 
	"RECORD_DATE_EDIT" NVARCHAR2(2000), 
	"SC_OFFICE" NVARCHAR2(2000), 
	"SERIAL_NO" NVARCHAR2(2000), 
	"SERIAL_NO_EDIT" NVARCHAR2(2000), 
	"SURVEY_RECORD1982" NVARCHAR2(2000), 
	"APPROVED_BY_POST" NVARCHAR2(2000), 
	"APPROVED_BY_USER" NVARCHAR2(2000), 
	"APPROVE_TYPE" NVARCHAR2(2000), 
	"RECOMMENDED_BY_POST" NVARCHAR2(2000), 
	"AMEND_DATE" TIMESTAMP (7), 
	"CASE_FILE" NVARCHAR2(2000), 
	"CLEARANCE_NO" NVARCHAR2(2000), 
	"JOB_NO" NVARCHAR2(2000), 
	"RECORD_DATE" TIMESTAMP (7), 
	"REINSTATE_REMARK" NVARCHAR2(2000), 
	 CONSTRAINT "PK_SQUATTER_PENDS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SC"."SQUATTER_PENDS" ADD CONSTRAINT "FK_SQUATTER_PENDS_DLOS_DLO_ID" FOREIGN KEY ("DLO_ID")
	  REFERENCES "SC"."DLOS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SC"."SQUATTER_PENDS" ADD CONSTRAINT "FK_SQUATTER_PENDS_SQUATTERS_SQUATTER_GUID" FOREIGN KEY ("SQUATTER_GUID")
	  REFERENCES "SC"."SQUATTERS" ("ID") ENABLE;

CREATE UNIQUE INDEX "SC"."PK_SQUATTER_PENDS" ON "SC"."SQUATTER_PENDS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_SQUATTER_PENDS_DLO_ID" ON "SC"."SQUATTER_PENDS" ("DLO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "SC"."IX_SQUATTER_PENDS_SQUATTER_ID" ON "SC"."SQUATTER_PENDS" ("SQUATTER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_SQUATTER_PENDS_SQUATTER_GUID" ON "SC"."SQUATTER_PENDS" ("SQUATTER_GUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."SQUATTER_USES" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"USE_ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"SQUATTER_GUID" NVARCHAR2(450), 
	"SQUATTER_PEND_GUID" NVARCHAR2(450), 
	"SQUATTER_ID" NUMBER(10,0), 
	"SQUATTER_VERSION" NUMBER(10,0) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	"OBJECT_ID" NUMBER(10,0), 
	"GLOBAL_ID" NVARCHAR2(2000), 
	"D_SQUATTER_USE_ID" NVARCHAR2(2000), 
	 CONSTRAINT "PK_SQUATTER_USES" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SC"."SQUATTER_USES" ADD CONSTRAINT "FK_SQUATTER_USES_SQUATTERS_SQUATTER_GUID" FOREIGN KEY ("SQUATTER_GUID")
	  REFERENCES "SC"."SQUATTERS" ("ID") ENABLE;
  ALTER TABLE "SC"."SQUATTER_USES" ADD CONSTRAINT "FK_SQUATTER_USES_SQUATTER_PENDS_SQUATTER_PEND_GUID" FOREIGN KEY ("SQUATTER_PEND_GUID")
	  REFERENCES "SC"."SQUATTER_PENDS" ("ID") ENABLE;
  ALTER TABLE "SC"."SQUATTER_USES" ADD CONSTRAINT "FK_SQUATTER_USES_USES_USE_ID" FOREIGN KEY ("USE_ID")
	  REFERENCES "SC"."USES" ("ID") ON DELETE CASCADE ENABLE;

CREATE UNIQUE INDEX "SC"."PK_SQUATTER_USES" ON "SC"."SQUATTER_USES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_SQUATTER_USES_SQUATTER_GUID" ON "SC"."SQUATTER_USES" ("SQUATTER_GUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_SQUATTER_USES_SQUATTER_PEND_GUID" ON "SC"."SQUATTER_USES" ("SQUATTER_PEND_GUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_SQUATTER_USES_USE_ID" ON "SC"."SQUATTER_USES" ("USE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."SQUATTER_USE_HIS" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"USE_ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"SQUATTER_HISTORY_ID" NVARCHAR2(450), 
	"SQUATTER_ID" NUMBER(10,0), 
	"SQUATTER_VERSION" NUMBER(10,0) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	"OBJECT_ID" NUMBER(10,0), 
	"GLOBAL_ID" NVARCHAR2(2000), 
	"D_SQUATTER_USE_ID" NVARCHAR2(2000), 
	 CONSTRAINT "PK_SQUATTER_USE_HIS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SC"."SQUATTER_USE_HIS" ADD CONSTRAINT "FK_SQUATTER_USE_HIS_SQUATTER_HISTORIES_SQUATTER_HISTORY_ID" FOREIGN KEY ("SQUATTER_HISTORY_ID")
	  REFERENCES "SC"."SQUATTER_HISTORIES" ("ID") ENABLE;
  ALTER TABLE "SC"."SQUATTER_USE_HIS" ADD CONSTRAINT "FK_SQUATTER_USE_HIS_USES_USE_ID" FOREIGN KEY ("USE_ID")
	  REFERENCES "SC"."USES" ("ID") ON DELETE CASCADE ENABLE;

CREATE UNIQUE INDEX "SC"."PK_SQUATTER_USE_HIS" ON "SC"."SQUATTER_USE_HIS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_SQUATTER_USE_HIS_SQUATTER_HISTORY_ID" ON "SC"."SQUATTER_USE_HIS" ("SQUATTER_HISTORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_SQUATTER_USE_HIS_USE_ID" ON "SC"."SQUATTER_USE_HIS" ("USE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."STAFFS" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"CSS_ID" NVARCHAR2(2000), 
	"CSS_UID" NVARCHAR2(2000), 
	"USERNAME" NVARCHAR2(2000), 
	"ENG_NAME" NVARCHAR2(2000), 
	"CHI_NAME" NVARCHAR2(2000), 
	"EMAIL" NVARCHAR2(2000), 
	"INTRANET_SMTP_EMAIL_ADDRESS" NVARCHAR2(2000), 
	"STAFF_STATUS" NVARCHAR2(2000), 
	"STAFF_TYPE" NVARCHAR2(2000), 
	"IS_ACTIVE" NUMBER(1,0) NOT NULL ENABLE, 
	"IS_FROM_CSS_RAW" NUMBER(1,0) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	 CONSTRAINT "PK_STAFFS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SC"."PK_STAFFS" ON "SC"."STAFFS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."STAFF_ACCESS_LOGS" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"POST_ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"IP" NVARCHAR2(2000), 
	"USER_AGENT" NVARCHAR2(2000), 
	"POSTNAME" NVARCHAR2(2000), 
	"USERNAME" NVARCHAR2(2000), 
	"DLONAME" NVARCHAR2(2000), 
	"LOGIN_AT" TIMESTAMP (7) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	 CONSTRAINT "PK_STAFF_ACCESS_LOGS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SC"."STAFF_ACCESS_LOGS" ADD CONSTRAINT "FK_STAFF_ACCESS_LOGS_POSTS_POST_ID" FOREIGN KEY ("POST_ID")
	  REFERENCES "SC"."POSTS" ("ID") ON DELETE CASCADE ENABLE;

CREATE UNIQUE INDEX "SC"."PK_STAFF_ACCESS_LOGS" ON "SC"."STAFF_ACCESS_LOGS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_STAFF_ACCESS_LOGS_POST_ID" ON "SC"."STAFF_ACCESS_LOGS" ("POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."STAFF_POSTS" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"POST_ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"STAFF_ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"ACTIVE_DATE" TIMESTAMP (7), 
	"IN_ACTIVATE_DATE" TIMESTAMP (7), 
	"IS_FROM_CSS_RAW" NUMBER(1,0) NOT NULL ENABLE, 
	"IS_ACTIVE" NUMBER(1,0) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	 CONSTRAINT "PK_STAFF_POSTS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SC"."STAFF_POSTS" ADD CONSTRAINT "FK_STAFF_POSTS_POSTS_POST_ID" FOREIGN KEY ("POST_ID")
	  REFERENCES "SC"."POSTS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SC"."STAFF_POSTS" ADD CONSTRAINT "FK_STAFF_POSTS_STAFFS_STAFF_ID" FOREIGN KEY ("STAFF_ID")
	  REFERENCES "SC"."STAFFS" ("ID") ON DELETE CASCADE ENABLE;

CREATE UNIQUE INDEX "SC"."PK_STAFF_POSTS" ON "SC"."STAFF_POSTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_STAFF_POSTS_POST_ID" ON "SC"."STAFF_POSTS" ("POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SC"."IX_STAFF_POSTS_STAFF_ID" ON "SC"."STAFF_POSTS" ("STAFF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."USES" 
   (	"ID" NVARCHAR2(450) NOT NULL ENABLE, 
	"NAME" NVARCHAR2(2000) NOT NULL ENABLE, 
	"DISPLAY_NAME" NVARCHAR2(2000) NOT NULL ENABLE, 
	"SORTING_INDEX" NUMBER(10,0) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (7), 
	"UPDATED_AT" TIMESTAMP (7), 
	 CONSTRAINT "PK_USES" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SC"."PK_USES" ON "SC"."USES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SC"."__EFMigrationsHistory" 
   (	"MIGRATION_ID" NVARCHAR2(150) NOT NULL ENABLE, 
	"PRODUCT_VERSION" NVARCHAR2(32) NOT NULL ENABLE, 
	 CONSTRAINT "PK___EF_MIGRATIONS_HISTORY" PRIMARY KEY ("MIGRATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SC"."PK___EF_MIGRATIONS_HISTORY" ON "SC"."__EFMigrationsHistory" ("MIGRATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE OR REPLACE PROCEDURE SC.find_dlo_id(
    p_dlooffice IN VARCHAR2,
    p_dlo_id OUT VARCHAR2
) IS
    v_dlo_ids VARCHAR2(4000);
BEGIN
    BEGIN
        -- Attempt to find a single ID based on the DLO_NAME
        SELECT ID
        INTO p_dlo_id
        FROM SC.DLOS dlos
        WHERE DLO_NAME LIKE '%' || '/' || p_dlooffice || '%'
            OR (p_dlooffice = 'N' AND DLO_NAME LIKE '%/ND%')
            OR (p_dlooffice = 'HKWS' AND DLO_NAME LIKE '%/HKW&S%')
            OR (p_dlooffice = 'KT' AND DLO_NAME LIKE '%/TW&KT%');

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            p_dlo_id := NULL;
            log_error('DLO', 'NO FOUND DLOOFFICE: ' || p_dlooffice, NULL);

        WHEN TOO_MANY_ROWS THEN
            p_dlo_id := NULL;
            
            -- Collect all IDs that match the condition to log them
            SELECT LISTAGG(ID, ', ') WITHIN GROUP (ORDER BY ID)
            INTO v_dlo_ids
            FROM SC.DLOS
            WHERE DLO_NAME LIKE '%' || p_dlooffice || '%';
            
            -- Log an error with the concatenated list of IDs for debugging
            log_error('DLO', 'Multiple records found for DLOOFFICE: ' || p_dlooffice || 
                             '. Found IDs: ' || v_dlo_ids,NULL);
    END;
END find_dlo_id;

CREATE OR REPLACE PROCEDURE SC.generate_Formatted_GUID(p_guid OUT VARCHAR2)
IS
    l_raw_guid RAW(16);
BEGIN
    l_raw_guid := sys_guid();
    p_guid := SUBSTR(rawtohex(l_raw_guid), 1, 8) || '-' ||
              SUBSTR(rawtohex(l_raw_guid), 9, 4) || '-' ||
              SUBSTR(rawtohex(l_raw_guid), 13, 4) || '-' ||
              SUBSTR(rawtohex(l_raw_guid), 17, 4) || '-' ||
              SUBSTR(rawtohex(l_raw_guid), 21, 12);
END;

CREATE OR REPLACE PROCEDURE SC.LOG_ERROR(
    p_table_name VARCHAR2,
    p_error_msg  VARCHAR2,
    p_object_id VARCHAR2 DEFAULT NULL
) IS
BEGIN
    INSERT INTO ERROR_LOG (TABLE_NAME, ERROR_MESSAGE, LOG_DATE, OBJECTID)
    VALUES (p_table_name, p_error_msg, SYSDATE, p_object_id);
    COMMIT;
END LOG_ERROR; 
;

CREATE SEQUENCE SC."ISEQ$$_75909" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;