-- DROP USER SDE_SQ;

CREATE USER SDE_SQ
-- IDENTIFIED BY <password>
;

CREATE TABLE "SDE_SQ"."DYNAMICVALUE" 
   (	"OBJECTID" NUMBER(38,0), 
	"TABLENAME" NVARCHAR2(254), 
	"FIELDNAME" NVARCHAR2(64), 
	"VALUEMETHOD" NVARCHAR2(254), 
	"VALUEINFO" NVARCHAR2(254), 
	"ON_CREATE" NUMBER(5,0), 
	"ON_CHANGE" NUMBER(5,0), 
	"ON_CHANGEGEO" NUMBER(5,0), 
	"ON_MANUAL" NUMBER(5,0), 
	"RUN_WEIGHT" NUMBER(5,0), 
	"COMMENTS" NVARCHAR2(255), 
	 CONSTRAINT "SYS_C009708" CHECK ("OBJECTID" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SDE_SQ"."R72_SDE_ROWID_UK" ON "SDE_SQ"."DYNAMICVALUE" ("OBJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SDE_SQ"."SCOFFICE_DLO" 
   (	"OBJECTID" NUMBER(38,0), 
	"SCOFFICE" NVARCHAR2(255), 
	"DLO" NVARCHAR2(255), 
	"FOLDER_NAME" NVARCHAR2(255), 
	"ID" NUMBER(38,8), 
	 CONSTRAINT "SYS_C009709" CHECK ("OBJECTID" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SDE_SQ"."R73_SDE_ROWID_UK" ON "SDE_SQ"."SCOFFICE_DLO" ("OBJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SDE_SQ"."SQUATTER" 
   (	"OBJECTID" NUMBER(38,0), 
	"SQUATTERID" NUMBER(10,0), 
	"DIMENSION_L" NUMBER(38,8), 
	"DIMENSION_B" NUMBER(38,8), 
	"DIMENSION_H" NUMBER(38,8), 
	"LOCATION" NVARCHAR2(150), 
	"DLOOFFICE" NVARCHAR2(50), 
	"FILENAME" NVARCHAR2(100), 
	"STATUS" NVARCHAR2(10), 
	"RECORDDATE" TIMESTAMP (6), 
	"SQUATTERDISTRICT" NVARCHAR2(50), 
	"PLANFILENAME" NVARCHAR2(100), 
	"CREATED_USER" NVARCHAR2(255), 
	"CREATED_DATE" TIMESTAMP (6), 
	"LAST_EDITED_USER" NVARCHAR2(255), 
	"LAST_EDITED_DATE" TIMESTAMP (6), 
	"CISSQUATTERID" NVARCHAR2(50), 
	"BOOKNO" NVARCHAR2(15), 
	"SERIALNO" NVARCHAR2(20), 
	"SURVEYNO" NVARCHAR2(5), 
	"FILEREF" NVARCHAR2(50), 
	"ISSUE" NUMBER(5,0), 
	"SCOFFICE" NVARCHAR2(20), 
	"SURVEYNOPREFIX" NVARCHAR2(30), 
	"HASREMARK" NVARCHAR2(2), 
	"HOUSENO" NVARCHAR2(100), 
	"DISPLAYNAME" NVARCHAR2(80), 
	"BOUNDARYSTATUS" NVARCHAR2(2), 
	"DIMENSIONUNIT" NVARCHAR2(2), 
	"SERIALNO_EDIT" NVARCHAR2(20), 
	"RECORDDATE_EDIT" NVARCHAR2(25), 
	"JOBNO" NVARCHAR2(50), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CASEFILE" NVARCHAR2(50), 
	"AMEND_DATE" TIMESTAMP (6), 
	"DELETE_REASON" NVARCHAR2(50), 
	"CLEARANCE_NO" NVARCHAR2(20), 
	"DELETE_DATE" TIMESTAMP (6), 
	"REINSTATE_DATE" TIMESTAMP (6), 
	"APPROVE_STATUS" NVARCHAR2(20), 
	"VERSION" NUMBER(10,0), 
	"SURVEYRECORD_1982" NVARCHAR2(5), 
	"APPROVED_CREATION_DATE" TIMESTAMP (6), 
	"APPROVED_DELETE_DATE" TIMESTAMP (6), 
	"APPROVED_REINSTATE_DATE" TIMESTAMP (6), 
	"APPROVED_AMEND_DATE" TIMESTAMP (6), 
	 CONSTRAINT "SYS_C009694" CHECK ("OBJECTID" IS NOT NULL) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE INDEX "SDE_SQ"."I1616LOCATION" ON "SDE_SQ"."SQUATTER" ("LOCATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SDE_SQ"."I1616SCOFFICE" ON "SDE_SQ"."SQUATTER" ("SCOFFICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SDE_SQ"."I1616SQUATTERDIS" ON "SDE_SQ"."SQUATTER" ("SQUATTERDISTRICT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SDE_SQ"."I1616SQUATTERID" ON "SDE_SQ"."SQUATTER" ("SQUATTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SDE_SQ"."I1616STATUS" ON "SDE_SQ"."SQUATTER" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SDE_SQ"."I1616SURVEYNO" ON "SDE_SQ"."SQUATTER" ("SURVEYNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SDE_SQ"."I1616SURVEYNOPRE" ON "SDE_SQ"."SQUATTER" ("SURVEYNOPREFIX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "SDE_SQ"."R65_SDE_ROWID_UK" ON "SDE_SQ"."SQUATTER" ("OBJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SDE_SQ"."SQUATTERDIMENSION" 
   (	"OBJECTID" NUMBER(38,0), 
	"SQUATTERID" NUMBER(10,0), 
	"SQUATTERDIMENSIONID" NUMBER(10,0), 
	"LENGTH_FOOT" NUMBER(38,8), 
	"BREADTH_FOOT" NUMBER(38,8), 
	"HEIGHT_FOOT" NUMBER(38,8), 
	"LENGTH_METRIC" NUMBER(38,8), 
	"BREADTH_METRIC" NUMBER(38,8), 
	"HEIGHT_METRIC" NUMBER(38,8), 
	"SQUATTERUSE" NVARCHAR2(50), 
	"GLOBALID" CHAR(38), 
	"CREATED_USER" NVARCHAR2(255), 
	"CREATED_DATE" TIMESTAMP (6), 
	"LAST_EDITED_USER" NVARCHAR2(255), 
	"LAST_EDITED_DATE" TIMESTAMP (6), 
	 CONSTRAINT "SYS_C009690" CHECK ("OBJECTID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C009691" CHECK ("SQUATTERID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C009692" CHECK ("SQUATTERDIMENSIONID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C009693" CHECK ("GLOBALID" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE INDEX "SDE_SQ"."G1615SQUATTERID" ON "SDE_SQ"."SQUATTERDIMENSION" ("SQUATTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "SDE_SQ"."R64_SDE_ROWID_UK" ON "SDE_SQ"."SQUATTERDIMENSION" ("OBJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "SDE_SQ"."UUID_64" ON "SDE_SQ"."SQUATTERDIMENSION" ("GLOBALID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SDE_SQ"."SQUATTERMATERIAL" 
   (	"OBJECTID" NUMBER(38,0), 
	"SQUATTERID" NUMBER(10,0), 
	"SQUATTERMATERIALID" NUMBER(10,0), 
	"MATERIALS" NVARCHAR2(50), 
	"GLOBALID" CHAR(38), 
	"CREATED_USER" NVARCHAR2(255), 
	"CREATED_DATE" TIMESTAMP (6), 
	"LAST_EDITED_USER" NVARCHAR2(255), 
	"LAST_EDITED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	 CONSTRAINT "SYS_C009686" CHECK ("OBJECTID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C009687" CHECK ("SQUATTERID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C009688" CHECK ("SQUATTERMATERIALID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C009689" CHECK ("GLOBALID" IS NOT NULL) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE INDEX "SDE_SQ"."G1614SQUATTERID" ON "SDE_SQ"."SQUATTERMATERIAL" ("SQUATTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "SDE_SQ"."R63_SDE_ROWID_UK" ON "SDE_SQ"."SQUATTERMATERIAL" ("OBJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "SDE_SQ"."UUID_63" ON "SDE_SQ"."SQUATTERMATERIAL" ("GLOBALID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

GRANT INSERT ON "SDE_SQ"."SQUATTERMATERIAL" TO "SC";
;

CREATE TABLE "SDE_SQ"."SQUATTERMATERIAL_HIS" 
   (	"OBJECTID" NUMBER(38,0), 
	"OBJECTID_1" NUMBER(10,0), 
	"SQUATTERID" NUMBER(10,0), 
	"SQUATTERMATERIALID" NUMBER(10,0), 
	"MATERIALS" NVARCHAR2(50), 
	"GLOBALID" CHAR(38), 
	"CREATED_USER" NVARCHAR2(255), 
	"CREATED_DATE" TIMESTAMP (6), 
	"LAST_EDITED_USER" NVARCHAR2(255), 
	"LAST_EDITED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	 CONSTRAINT "SYS_C009697" CHECK ("OBJECTID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C009698" CHECK ("OBJECTID_1" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C009699" CHECK ("SQUATTERID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C009700" CHECK ("SQUATTERMATERIALID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C009701" CHECK ("GLOBALID" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SDE_SQ"."R67_SDE_ROWID_UK" ON "SDE_SQ"."SQUATTERMATERIAL_HIS" ("OBJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SDE_SQ"."SQUATTERUSE" 
   (	"OBJECTID" NUMBER(38,0), 
	"SQUATTERID" NUMBER(10,0), 
	"SQUATTERUSEID" NUMBER(10,0), 
	"SQUATTERUSE" NVARCHAR2(50), 
	"GLOBALID" CHAR(38), 
	"CREATED_USER" NVARCHAR2(255), 
	"CREATED_DATE" TIMESTAMP (6), 
	"LAST_EDITED_USER" NVARCHAR2(255), 
	"LAST_EDITED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	 CONSTRAINT "SYS_C009684" CHECK ("OBJECTID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C009685" CHECK ("GLOBALID" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE INDEX "SDE_SQ"."G1613SQUATTERID" ON "SDE_SQ"."SQUATTERUSE" ("SQUATTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "SDE_SQ"."R62_SDE_ROWID_UK" ON "SDE_SQ"."SQUATTERUSE" ("OBJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "SDE_SQ"."UUID_62" ON "SDE_SQ"."SQUATTERUSE" ("GLOBALID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SDE_SQ"."SQUATTERUSE_HIS" 
   (	"OBJECTID" NUMBER(38,0), 
	"OBJECTID_1" NUMBER(10,0), 
	"SQUATTERID" NUMBER(10,0), 
	"SQUATTERUSEID" NUMBER(10,0), 
	"SQUATTERUSE" NVARCHAR2(50), 
	"GLOBALID" CHAR(38), 
	"CREATED_USER" NVARCHAR2(255), 
	"CREATED_DATE" TIMESTAMP (6), 
	"LAST_EDITED_USER" NVARCHAR2(255), 
	"LAST_EDITED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	 CONSTRAINT "SYS_C009702" CHECK ("OBJECTID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C009703" CHECK ("OBJECTID_1" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C009704" CHECK ("GLOBALID" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SDE_SQ"."R68_SDE_ROWID_UK" ON "SDE_SQ"."SQUATTERUSE_HIS" ("OBJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SDE_SQ"."SQUATTER_DASHBOARD" 
   (	"OBJECTID" NUMBER(38,0), 
	"SQUATTERID" NUMBER(10,0), 
	"DIMENSION_L" NUMBER(38,8), 
	"DIMENSION_B" NUMBER(38,8), 
	"DIMENSION_H" NUMBER(38,8), 
	"LOCATION" NVARCHAR2(150), 
	"DLOOFFICE" NVARCHAR2(50), 
	"FILENAME" NVARCHAR2(100), 
	"STATUS" NVARCHAR2(10), 
	"RECORDDATE" TIMESTAMP (6), 
	"SQUATTERDISTRICT" NVARCHAR2(50), 
	"PLANFILENAME" NVARCHAR2(100), 
	"CREATED_USER" NVARCHAR2(255), 
	"CREATED_DATE" TIMESTAMP (6), 
	"LAST_EDITED_USER" NVARCHAR2(255), 
	"LAST_EDITED_DATE" TIMESTAMP (6), 
	"CISSQUATTERID" NVARCHAR2(50), 
	"BOOKNO" NVARCHAR2(15), 
	"SERIALNO" NVARCHAR2(20), 
	"SURVEYNO" NVARCHAR2(5), 
	"FILEREF" NVARCHAR2(50), 
	"ISSUE" NUMBER(5,0), 
	"SCOFFICE" NVARCHAR2(20), 
	"SURVEYNOPREFIX" NVARCHAR2(30), 
	"HASREMARK" NVARCHAR2(2), 
	"HOUSENO" NVARCHAR2(100), 
	"DISPLAYNAME" NVARCHAR2(80), 
	"BOUNDARYSTATUS" NVARCHAR2(2), 
	"DIMENSIONUNIT" NVARCHAR2(2), 
	"SERIALNO_EDIT" NVARCHAR2(20), 
	"RECORDDATE_EDIT" NVARCHAR2(25), 
	"JOBNO" NVARCHAR2(50), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CASEFILE" NVARCHAR2(50), 
	"AMEND_DATE" TIMESTAMP (6), 
	"DELETE_REASON" NVARCHAR2(50), 
	"CLEARANCE_NO" NVARCHAR2(20), 
	"DELETE_DATE" TIMESTAMP (6), 
	"REINSTATE_DATE" TIMESTAMP (6), 
	"APPROVE_STATUS" NVARCHAR2(20), 
	"VERSION" NUMBER(10,0), 
	"SDE_STATE_ID" NUMBER(19,0), 
	"GIRS2_USE" NVARCHAR2(99), 
	"GIRS2_MATERIAL" NVARCHAR2(99), 
	"DSO" NVARCHAR2(50), 
	"SURVEYNOPREFIX_SURVEYNO" NVARCHAR2(35), 
	"PDF_FILEPATH" NVARCHAR2(200), 
	"SURVEYRECORD_1982" NVARCHAR2(5), 
	"REPAIR_REBUILD" NVARCHAR2(200), 
	"VRS" NVARCHAR2(200), 
	"VRS_PDF" NVARCHAR2(2), 
	"REPAIR_REBUILD_PDF" NVARCHAR2(2), 
	"APPROVED_CREATION_DATE" TIMESTAMP (6), 
	"APPROVED_DELETE_DATE" TIMESTAMP (6), 
	"APPROVED_REINSTATE_DATE" TIMESTAMP (6), 
	"APPROVED_AMEND_DATE" TIMESTAMP (6), 
	"SHAPE" "ST_GEOMETRY", 
	 CONSTRAINT "SYS_C009710" CHECK ("OBJECTID" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SDE_SQ"."SYS_IL0000075446C00065$$" ON "SDE_SQ"."SQUATTER_DASHBOARD" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "SDE_SQ"."SYS_IL0000075446C00064$$" ON "SDE_SQ"."SQUATTER_DASHBOARD" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE INDEX "SDE_SQ"."I2576CISSQUATTER" ON "SDE_SQ"."SQUATTER_DASHBOARD" ("CISSQUATTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SDE_SQ"."I2576DLOOFFICE" ON "SDE_SQ"."SQUATTER_DASHBOARD" ("DLOOFFICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SDE_SQ"."I2576LOCATION" ON "SDE_SQ"."SQUATTER_DASHBOARD" ("LOCATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SDE_SQ"."I2576SCOFFICE" ON "SDE_SQ"."SQUATTER_DASHBOARD" ("SCOFFICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SDE_SQ"."I2576SQUATTERDIS" ON "SDE_SQ"."SQUATTER_DASHBOARD" ("SQUATTERDISTRICT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SDE_SQ"."I2576SQUATTERID" ON "SDE_SQ"."SQUATTER_DASHBOARD" ("SQUATTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SDE_SQ"."I2576STATUS" ON "SDE_SQ"."SQUATTER_DASHBOARD" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "SDE_SQ"."R74_SDE_ROWID_UK" ON "SDE_SQ"."SQUATTER_DASHBOARD" ("OBJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SDE_SQ"."SQUATTER_GIRS" 
   (	"OBJECTID" NUMBER(38,0), 
	"SQUATTERID" NUMBER(10,0), 
	"DIMENSION_L" NUMBER(38,8), 
	"DIMENSION_B" NUMBER(38,8), 
	"DIMENSION_H" NUMBER(38,8), 
	"LOCATION" NVARCHAR2(150), 
	"DLOOFFICE" NVARCHAR2(50), 
	"FILENAME" NVARCHAR2(100), 
	"STATUS" NVARCHAR2(10), 
	"RECORDDATE" TIMESTAMP (6), 
	"SQUATTERDISTRICT" NVARCHAR2(50), 
	"PLANFILENAME" NVARCHAR2(100), 
	"CREATED_USER" NVARCHAR2(255), 
	"CREATED_DATE" TIMESTAMP (6), 
	"LAST_EDITED_USER" NVARCHAR2(255), 
	"LAST_EDITED_DATE" TIMESTAMP (6), 
	"CISSQUATTERID" NVARCHAR2(50), 
	"BOOKNO" NVARCHAR2(15), 
	"SERIALNO" NVARCHAR2(20), 
	"SURVEYNO" NVARCHAR2(5), 
	"FILEREF" NVARCHAR2(50), 
	"ISSUE" NUMBER(5,0), 
	"SCOFFICE" NVARCHAR2(20), 
	"SURVEYNOPREFIX" NVARCHAR2(30), 
	"HASREMARK" NVARCHAR2(2), 
	"HOUSENO" NVARCHAR2(100), 
	"DISPLAYNAME" NVARCHAR2(80), 
	"BOUNDARYSTATUS" NVARCHAR2(2), 
	"DIMENSIONUNIT" NVARCHAR2(2), 
	"SERIALNO_EDIT" NVARCHAR2(20), 
	"RECORDDATE_EDIT" NVARCHAR2(25), 
	"JOBNO" NVARCHAR2(50), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CASEFILE" NVARCHAR2(50), 
	"AMEND_DATE" TIMESTAMP (6), 
	"DELETE_REASON" NVARCHAR2(50), 
	"CLEARANCE_NO" NVARCHAR2(20), 
	"DELETE_DATE" TIMESTAMP (6), 
	"REINSTATE_DATE" TIMESTAMP (6), 
	"APPROVE_STATUS" NVARCHAR2(20), 
	"VERSION" NUMBER(10,0), 
	"SDE_STATE_ID" NUMBER(19,0), 
	"GIRS2_USE" NVARCHAR2(99), 
	"GIRS2_MATERIAL" NVARCHAR2(99), 
	"DSO" NVARCHAR2(50), 
	"SURVEYNOPREFIX_SURVEYNO" NVARCHAR2(35), 
	"PDF_FILEPATH" NVARCHAR2(200), 
	"SURVEYRECORD_1982" NVARCHAR2(5), 
	"REPAIR_REBUILD" NVARCHAR2(200), 
	"VRS" NVARCHAR2(200), 
	"APPROVED_CREATION_DATE" TIMESTAMP (6), 
	"APPROVED_DELETE_DATE" TIMESTAMP (6), 
	"APPROVED_REINSTATE_DATE" TIMESTAMP (6), 
	"APPROVED_AMEND_DATE" TIMESTAMP (6), 
	"SHAPE" "ST_GEOMETRY", 
	 CONSTRAINT "SYS_C009716" CHECK ("OBJECTID" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SDE_SQ"."SYS_IL0000075459C00063$$" ON "SDE_SQ"."SQUATTER_GIRS" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "SDE_SQ"."SYS_IL0000075459C00062$$" ON "SDE_SQ"."SQUATTER_GIRS" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE INDEX "SDE_SQ"."I2578CISSQUATTER" ON "SDE_SQ"."SQUATTER_GIRS" ("CISSQUATTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SDE_SQ"."I2578DLOOFFICE" ON "SDE_SQ"."SQUATTER_GIRS" ("DLOOFFICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SDE_SQ"."I2578LOCATION" ON "SDE_SQ"."SQUATTER_GIRS" ("LOCATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SDE_SQ"."I2578SCOFFICE" ON "SDE_SQ"."SQUATTER_GIRS" ("SCOFFICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SDE_SQ"."I2578SQUATTERDIS" ON "SDE_SQ"."SQUATTER_GIRS" ("SQUATTERDISTRICT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SDE_SQ"."I2578SQUATTERID" ON "SDE_SQ"."SQUATTER_GIRS" ("SQUATTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "SDE_SQ"."I2578STATUS" ON "SDE_SQ"."SQUATTER_GIRS" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "SDE_SQ"."R76_SDE_ROWID_UK" ON "SDE_SQ"."SQUATTER_GIRS" ("OBJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SDE_SQ"."SQUATTER_HIS" 
   (	"OBJECTID" NUMBER(38,0), 
	"OBJECTID_1" NUMBER(10,0), 
	"SQUATTERID" NUMBER(10,0), 
	"DIMENSION_L" NUMBER(38,8), 
	"DIMENSION_B" NUMBER(38,8), 
	"DIMENSION_H" NUMBER(38,8), 
	"LOCATION" NVARCHAR2(150), 
	"DLOOFFICE" NVARCHAR2(50), 
	"FILENAME" NVARCHAR2(100), 
	"STATUS" NVARCHAR2(10), 
	"RECORDDATE" TIMESTAMP (6), 
	"SQUATTERDISTRICT" NVARCHAR2(50), 
	"PLANFILENAME" NVARCHAR2(100), 
	"CREATED_USER" NVARCHAR2(255), 
	"CREATED_DATE" TIMESTAMP (6), 
	"LAST_EDITED_USER" NVARCHAR2(255), 
	"LAST_EDITED_DATE" TIMESTAMP (6), 
	"CISSQUATTERID" NVARCHAR2(50), 
	"BOOKNO" NVARCHAR2(15), 
	"SERIALNO" NVARCHAR2(20), 
	"SURVEYNO" NVARCHAR2(5), 
	"FILEREF" NVARCHAR2(50), 
	"ISSUE" NUMBER(2,0), 
	"SCOFFICE" NVARCHAR2(20), 
	"SURVEYNOPREFIX" NVARCHAR2(30), 
	"HASREMARK" NVARCHAR2(2), 
	"HOUSENO" NVARCHAR2(100), 
	"DISPLAYNAME" NVARCHAR2(80), 
	"BOUNDARYSTATUS" NVARCHAR2(2), 
	"DIMENSIONUNIT" NVARCHAR2(2), 
	"SERIALNO_EDIT" NVARCHAR2(20), 
	"RECORDDATE_EDIT" NVARCHAR2(25), 
	"JOBNO" NVARCHAR2(50), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CASEFILE" NVARCHAR2(50), 
	"AMEND_DATE" TIMESTAMP (6), 
	"DELETE_REASON" NVARCHAR2(50), 
	"CLEARANCE_NO" NVARCHAR2(20), 
	"DELETE_DATE" TIMESTAMP (6), 
	"REINSTATE_DATE" TIMESTAMP (6), 
	"APPROVE_STATUS" NVARCHAR2(20), 
	"VERSION" NUMBER(10,0), 
	"SURVEYRECORD_1982" NVARCHAR2(5), 
	"APPROVED_CREATION_DATE" TIMESTAMP (6), 
	"APPROVED_DELETE_DATE" TIMESTAMP (6), 
	"APPROVED_REINSTATE_DATE" TIMESTAMP (6), 
	"APPROVED_AMEND_DATE" TIMESTAMP (6), 
	 CONSTRAINT "SYS_C009695" CHECK ("OBJECTID" IS NOT NULL) ENABLE, 
	 CONSTRAINT "SYS_C009696" CHECK ("OBJECTID_1" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SDE_SQ"."R66_SDE_ROWID_UK" ON "SDE_SQ"."SQUATTER_HIS" ("OBJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SDE_SQ"."SQUATTER_POLY" 
   (	"OBJECTID" NUMBER(38,0), 
	"SQUATTERID" NUMBER(10,0), 
	"CREATED_USER" NVARCHAR2(255), 
	"CREATED_DATE" TIMESTAMP (6), 
	"LAST_EDITED_USER" NVARCHAR2(255), 
	"LAST_EDITED_DATE" TIMESTAMP (6), 
	"SHAPE" "ST_GEOMETRY", 
	 CONSTRAINT "SYS_C009671" CHECK ("OBJECTID" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SDE_SQ"."SYS_IL0000075474C00015$$" ON "SDE_SQ"."SQUATTER_POLY" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "SDE_SQ"."SYS_IL0000075474C00014$$" ON "SDE_SQ"."SQUATTER_POLY" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE INDEX "SDE_SQ"."G1612SQUATTERID" ON "SDE_SQ"."SQUATTER_POLY" ("SQUATTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "SDE_SQ"."R61_SDE_ROWID_UK" ON "SDE_SQ"."SQUATTER_POLY" ("OBJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SDE_SQ"."SQUATTER_REPAIR_REBUILD" 
   (	"OBJECTID" NUMBER(38,0), 
	"SQUATTERID" NUMBER(10,0), 
	 CONSTRAINT "SYS_C009705" CHECK ("OBJECTID" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SDE_SQ"."R69_SDE_ROWID_UK" ON "SDE_SQ"."SQUATTER_REPAIR_REBUILD" ("OBJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SDE_SQ"."SQUATTER_TEMP" 
   (	"OBJECTID" NUMBER(38,0), 
	"OBJECTID_1" NUMBER(10,0), 
	"SQUATTERID" NUMBER(10,0), 
	"DIMENSION_L" NUMBER(38,8), 
	"DIMENSION_B" NUMBER(38,8), 
	"DIMENSION_H" NUMBER(38,8), 
	"LOCATION" NVARCHAR2(150), 
	"DLOOFFICE" NVARCHAR2(50), 
	"FILENAME" NVARCHAR2(100), 
	"STATUS" NVARCHAR2(10), 
	"RECORDDATE" TIMESTAMP (6), 
	"SQUATTERDISTRICT" NVARCHAR2(50), 
	"PLANFILENAME" NVARCHAR2(100), 
	"CREATED_USER" NVARCHAR2(255), 
	"CREATED_DATE" TIMESTAMP (6), 
	"LAST_EDITED_USER" NVARCHAR2(255), 
	"LAST_EDITED_DATE" TIMESTAMP (6), 
	"CISSQUATTERID" NVARCHAR2(50), 
	"BOOKNO" NVARCHAR2(15), 
	"SERIALNO" NVARCHAR2(20), 
	"SURVEYNO" NVARCHAR2(5), 
	"FILEREF" NVARCHAR2(50), 
	"ISSUE" NUMBER(5,0), 
	"SCOFFICE" NVARCHAR2(20), 
	"SURVEYNOPREFIX" NVARCHAR2(30), 
	"HASREMARK" NVARCHAR2(2), 
	"HOUSENO" NVARCHAR2(100), 
	"DISPLAYNAME" NVARCHAR2(80), 
	"BOUNDARYSTATUS" NVARCHAR2(2), 
	"DIMENSIONUNIT" NVARCHAR2(2), 
	"SERIALNO_EDIT" NVARCHAR2(20), 
	"RECORDDATE_EDIT" NVARCHAR2(25), 
	"JOBNO" NVARCHAR2(50), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CASEFILE" NVARCHAR2(50), 
	"AMEND_DATE" TIMESTAMP (6), 
	"DELETE_REASON" NVARCHAR2(50), 
	"CLEARANCE_NO" NVARCHAR2(20), 
	"DELETE_DATE" TIMESTAMP (6), 
	"REINSTATE_DATE" TIMESTAMP (6), 
	"APPROVE_STATUS" NVARCHAR2(20), 
	"VERSION" NUMBER(10,0), 
	"SURVEYRECORD_1982" NVARCHAR2(5), 
	"SDE_STATE_ID" NUMBER(19,0), 
	"APPROVED_CREATION_DATE" TIMESTAMP (6), 
	"APPROVED_DELETE_DATE" TIMESTAMP (6), 
	"APPROVED_REINSTATE_DATE" TIMESTAMP (6), 
	"APPROVED_AMEND_DATE" TIMESTAMP (6), 
	"GIRS2_USE" NVARCHAR2(99), 
	"GIRS2_MATERIAL" NVARCHAR2(99), 
	"GDB_GEOMATTR_DATA" BLOB, 
	"DSO" NVARCHAR2(50), 
	"SURVEYNOPREFIX_SURVEYNO" NVARCHAR2(50), 
	"PDF_FILEPATH" NVARCHAR2(200), 
	"REPAIR_REBUILD" NVARCHAR2(200), 
	"VRS" NVARCHAR2(200), 
	"SHAPE" "ST_GEOMETRY", 
	 CONSTRAINT "SYS_C009713" CHECK ("OBJECTID" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("GDB_GEOMATTR_DATA") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;

CREATE UNIQUE INDEX "SDE_SQ"."SYS_IL0000075483C00065$$" ON "SDE_SQ"."SQUATTER_TEMP" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "SDE_SQ"."SYS_IL0000075483C00064$$" ON "SDE_SQ"."SQUATTER_TEMP" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "SDE_SQ"."SYS_IL0000075483C00051$$" ON "SDE_SQ"."SQUATTER_TEMP" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "SDE_SQ"."R75_SDE_ROWID_UK" ON "SDE_SQ"."SQUATTER_TEMP" ("OBJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SDE_SQ"."SQUATTER_UPLOAD" 
   (	"OBJECTID" NUMBER(38,0), 
	"NAME" NVARCHAR2(500), 
	"CREATED_DATE" TIMESTAMP (6), 
	"FILE_TYPE" NVARCHAR2(50), 
	"DLO" NVARCHAR2(50), 
	"SQUATTERID" NUMBER(10,0), 
	 CONSTRAINT "SYS_C009707" CHECK ("OBJECTID" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SDE_SQ"."R71_SDE_ROWID_UK" ON "SDE_SQ"."SQUATTER_UPLOAD" ("OBJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SDE_SQ"."SQUATTER_VRS" 
   (	"OBJECTID" NUMBER(38,0), 
	"SQUATTERID" NUMBER(10,0), 
	 CONSTRAINT "SYS_C009706" CHECK ("OBJECTID" IS NOT NULL) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SDE_SQ"."R70_SDE_ROWID_UK" ON "SDE_SQ"."SQUATTER_VRS" ("OBJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
;