-- This SQL query provides a comprehensive comparison of record counts between source tables in the SDE_SQ schema and their corresponding target tables in the SC schema. It helps verify the success of data migration processes by listing the total number of records in the source tables (TOTAL) alongside the successfully migrated records in the target tables (SUCCESS). This query is especially useful for auditing, reporting, and ensuring data consistency post-migration.

SELECT 'SQUATTER' AS "TABLE_NAME",
       (SELECT COUNT(*) FROM SDE_SQ.SQUATTER) AS "TOTAL",
       (SELECT COUNT(*) FROM SQ.SQUATTERS s WHERE s.OBJECT_ID IS NOT NULL AND s.OBJECT_ID IN (SELECT OBJECTID FROM SDE_SQ.SQUATTER)) AS "SUCCESS"
FROM dual
UNION ALL
SELECT 'SQUATTER_HIS' AS "TABLE_NAME",
       (SELECT COUNT(*) FROM SDE_SQ.SQUATTER_HIS) AS "TOTAL",
       (SELECT COUNT(*) FROM SQ.SQUATTER_HISTORIES s WHERE s.OBJECT_ID IS NOT NULL AND s.OBJECT_ID IN (SELECT OBJECTID FROM SDE_SQ.SQUATTER_HIS) ) AS "SUCCESS"
FROM dual
UNION ALL
SELECT 'SQUATTER_PEND' AS "TABLE_NAME",
       (SELECT COUNT(*) FROM SDE_SQ.SQUATTER_PRO) AS "TOTAL",
       (SELECT COUNT(*) FROM SQ.SQUATTER_PENDS s WHERE s.OBJECT_ID IS NOT NULL AND s.OBJECT_ID IN (SELECT OBJECTID FROM SDE_SQ.SQUATTER_PRO) ) AS "SUCCESS"
FROM dual
UNION ALL
SELECT 'SQUATTER_USE & SQUATTER_MATERIAL_PRO' AS "TABLE_NAME",
       (SELECT COUNT(*) FROM (SELECT OBJECTID FROM SDE_SQ.SQUATTERUSE UNION ALL SELECT OBJECTID FROM SDE_SQ.SQUATTERUSE_PRO)) AS "TOTAL",
       (SELECT COUNT(*) FROM (SELECT OBJECTID FROM SQ.SQUATTER_USES s WHERE s.OBJECT_ID IS NOT NULL AND s.OBJECT_ID IN (SELECT OBJECTID FROM SDE_SQ.SQUATTERUSE))) AS "SUCCESS"
FROM dual
UNION ALL
SELECT 'SQUATTER_MATERIAL & SQUATTER_MATERIAL_PRO' AS "TABLE_NAME",
       (SELECT COUNT(*) FROM (SELECT OBJECTID FROM SDE_SQ.SQUATTERMATERIAL UNION ALL SELECT OBJECTID FROM SDE_SQ.SQUATTERMATERIAL_PRO)) AS "TOTAL",
       (SELECT COUNT(*) FROM (SELECT OBJECTID FROM SQ.SQUATTER_MATERIALS s WHERE s.OBJECT_ID IS NOT NULL AND s.OBJECT_ID IN (SELECT OBJECTID FROM SDE_SQ.SQUATTERMATERIAL))) AS "SUCCESS"
FROM dual
UNION ALL
SELECT 'SQUATTER_USE_HIS' AS "TABLE_NAME",
       (SELECT COUNT(*) FROM SDE_SQ.SQUATTERUSE_HIS) AS "TOTAL",
       (SELECT COUNT(*) FROM SQ.SQUATTER_USE_HIS s WHERE s.OBJECT_ID IS NOT NULL AND s.OBJECT_ID IN (SELECT OBJECTID FROM SDE_SQ.SQUATTERUSE_HIS)) AS "SUCCESS"
FROM dual
UNION ALL
SELECT 'SQUATTER_MATERIAL_HIS' AS "TABLE_NAME",
       (SELECT COUNT(*) FROM SDE_SQ.SQUATTERMATERIAL_HIS) AS "TOTAL",
       (SELECT COUNT(*) FROM SQ.SQUATTER_MATERIAL_HIS s WHERE s.OBJECT_ID IS NOT NULL AND s.OBJECT_ID IN (SELECT OBJECTID FROM SDE_SQ.SQUATTERMATERIAL_HIS sh)) AS "SUCCESS"
FROM dual
UNION ALL
SELECT 'ATTACHMENT' AS "TABLE_NAME",
       (SELECT COUNT(*) FROM SDE_SQ.SQUATTER_UPLOAD) AS "TOTAL",
       (SELECT COUNT(*) FROM SQ.ATTACHMENTS s WHERE s.OBJECT_ID IS NOT NULL AND s.OBJECT_ID IN (SELECT OBJECTID FROM SDE_SQ.SQUATTER_UPLOAD)) AS "SUCCESS"
FROM dual;