SELECT 
    s.DLOOFFICE, 
    COUNT(s.DLOOFFICE) AS "ORIGINAL SC COUNT",
    COUNT(CASE 
            WHEN s2.OBJECT_ID IN (SELECT OBJECTID FROM SDE_SQ.SQUATTER) 
            THEN s2.DLO_ID 
         END) AS "TARGET SC COUNT"
FROM 
    SDE_SQ.SQUATTER s
LEFT JOIN 
    SC.SQUATTERS s2 
    ON s.OBJECTID = s2.OBJECT_ID
GROUP BY 
    s.DLOOFFICE;