SELECT 'MATERIAL' AS "TABLE_NAME",
       (SELECT COUNT(DISTINCT(MATERIALS)) FROM SDE_SQ.SQUATTERMATERIAL) AS "TOTAL TYPE OF MATERIAL",
       (
SELECT COUNT(DISTINCT MATERIAL_ID) FROM (
	SELECT sm.MATERIAL_ID FROM SQ.SQUATTER_MATERIALS sm 
	UNION ALL 
	SELECT smh.MATERIAL_ID FROM SQ.SQUATTER_MATERIAL_HIS smh )
       ) AS "SUCCESS"
FROM DUAL
UNION ALL
SELECT 'USE' AS "TABLE_NAME",
       (SELECT COUNT(DISTINCT(SQUATTERUSE)) FROM SDE_SQ.SQUATTERUSE) AS "TOTAL TYPE OF USE",
       (
SELECT COUNT(DISTINCT USE_ID) FROM (
	SELECT sm.USE_ID FROM SQ.SQUATTER_USES sm 
	UNION ALL 
	SELECT smh.USE_ID FROM SQ.SQUATTER_USE_HIS smh )
       ) AS "SUCCESS"
FROM DUAL;