SELECT 'MATERIAL' AS "TABLE_NAME",
       (SELECT COUNT(DISTINCT(MATERIALS)) FROM SDE_SQ.SQUATTERMATERIAL) AS "TOTAL TYPE OF MATERIAL",
       (
SELECT COUNT(DISTINCT u.NAME)
FROM SQ.MATERIALS u 
LEFT JOIN SQ.SQUATTER_MATERIALS su ON u.ID = su.MATERIAL_ID AND su.OBJECT_ID IS NOT NULL AND su.OBJECT_ID IN (SELECT OBJECTID FROM SDE_SQ.SQUATTERMATERIAL s)
LEFT JOIN SQ.SQUATTER_MATERIAL_HIS suh ON u.ID = suh.MATERIAL_ID AND suh.OBJECT_ID IS NOT NULL AND suh.OBJECT_ID IN (SELECT OBJECTID FROM SDE_SQ.SQUATTERMATERIAL_HIS sh )
WHERE su.MATERIAL_ID IS NOT NULL OR suh.MATERIAL_ID IS NOT NULL
       ) AS "SUCCESS"
FROM DUAL
UNION ALL
SELECT 'USE' AS "TABLE_NAME",
       (SELECT COUNT(DISTINCT(SQUATTERUSE)) FROM SDE_SQ.SQUATTERUSE) AS "TOTAL TYPE OF USE",
       (
SELECT COUNT(DISTINCT u.NAME)
FROM SQ.USES u 
LEFT JOIN SQ.SQUATTER_USES su ON u.ID = su.USE_ID AND su.OBJECT_ID IS NOT NULL AND su.OBJECT_ID IN (SELECT OBJECTID FROM SDE_SQ.SQUATTERUSE s)
LEFT JOIN SQ.SQUATTER_USE_HIS suh ON u.ID = suh.USE_ID AND suh.OBJECT_ID IS NOT NULL AND suh.OBJECT_ID IN (SELECT OBJECTID FROM SDE_SQ.SQUATTERUSE_HIS sh )
WHERE su.USE_ID IS NOT NULL OR suh.USE_ID IS NOT NULL
       ) AS "SUCCESS"
FROM DUAL;
