CREATE OR REPLACE VIEW LICENCEANDPERMIT AS 
SELECT
g.id AS GLL_ID,
g.gll_no,
g."GLL_STATUS",
jt.LICENCEANDPERMITPOLYID,
NULL AS LICENCEANDPERMITLINEID,
l.LAOGLLNO
FROM glls g
LEFT JOIN 
     JSON_TABLE(
       g.POLYGON,
       '$[*]'
       COLUMNS (
         LICENCEANDPERMITPOLYID VARCHAR2(4000) PATH '$'
       )
     ) jt 
ON (1=1)
LEFT JOIN LICENCEANDPERMITPOLY l ON jt.LICENCEANDPERMITPOLYID = l.LICENCEANDPERMITPOLYID
UNION ALL 
SELECT
g.id AS GLL_ID,
g.gll_no,
g.GLL_STATUS,
NULL AS LICENCEANDPERMITPOLYID,
jt.LICENCEANDPERMITLINEID,
NULL AS LAOGLLNO
FROM glls g LEFT JOIN 
     JSON_TABLE(
       g.POLYLINE,
       '$[*]'
       COLUMNS (
         LICENCEANDPERMITLINEID VARCHAR2(4000) PATH '$'
       )
     ) jt 
ON (1=1)
;
