CREATE VIEW LICENCEANDPERMIT AS 
SELECT
glls.id,
glls.gll_no,
glls.GLL_STATUS,
jt.LICENCEANDPERMITPOLYID,
NULL AS LICENCEANDPERMITLINEID,
l.LAOGLLNO,
FROM glls g
LEFT JOIN 
     JSON_TABLE(
       glls.LICENCEANDPERMITPOLYID,
       '$[*]'
       COLUMNS (
         POLY_ID VARCHAR2(4000) PATH '$'
       )
     ) jt 
ON (1=1)
LEFT JOIN LICENCEANDPERMITPOLY l ON jt.LICENCEANDPERMITPOLYID = l.LICENCEANDPERMITPOLYID
ON jt.L = l.GLL_NO
UNION ALL 
SELECT
glls.id,
glls.gll_no,
glls.GLL_STATUS,
NULL AS LICENCEANDPERMITPOLYID,
jt.LICENCEANDPERMITLINEID,
NULL AS LAOGLLNO
FROM glls LEFT JOIN 
     JSON_TABLE(
       glls.LICENCEANDPERMITLINEID,
       '$[*]'
       COLUMNS (
         POLY_ID VARCHAR2(4000) PATH '$'
       )
     ) jt 
ON (1=1)
;

SELECT COUNT (*) FROM GLLS;